version: '3.5'

services:

    angular-service:

      container_name: angularcontainer

      build: ./angularapp2

      volumes:

        - './angularapp2:/usr/src/app' 

      ports: 

        - '8000:8000' # Port mapping

      command: bash -c "npm install -g @angular/cli && ng update @angular/cli --migrate-only --from=6.4.1 --allow-dirty && ng serve --host 0.0.0.0 --port 4200"
